### ISSUE TITLE
'Get Details' including subdomain

### ISSUE THREAD

**Issue by bdrehmer** [jefflau/ens-manager#25]
When you search for a path that includes a subdomain, the node shows up in the right half of the GUI, but no info appears on the left half of the GUI (all Node Details and Resolver Details are blank)

**Comment by bdrehmer** [comment]
it does know the owner of the subdomain if you search for the domain itself and then 'check for subdomain'

**Comment by jefflau** [comment]
My current implementation because of the way UI is built doesn't currently support searching sub domains. I'll consider adding this feature later as it will involve some rewriting of the application. I've added some error messages for now so it's clear that you need to search a root domain and stops you from searching

**Comment by jefflau** [comment]
Closing this for now. Will consider searching subdomains at a later date after the main implementation is bug free and feature complete. 

https://github.com/jefflau/ens-manager/commit/4efcaa0481a4175f65da6bea6f4ac88daafb825c
